"""S5 KnowledgeQuery types: source/entity/time/exact identifier/filter/top-k/evidence requirement.

事实源：S5 spec §5、ADR-006。
"""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class _FrozenModel(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")


class QuerySource(StrEnum):
    """Knowledge source type for query routing."""

    DOC = "doc"
    CODE = "code"
    GITHUB = "github"
    DB = "db"
    CROSS_SOURCE = "cross_source"


class EvidenceRequirement(StrEnum):
    """Evidence requirement level for a query."""

    ANY = "any"
    FRESH = "fresh"
    REPRODUCIBLE = "reproducible"
    NONE = "none"


class SortField(StrEnum):
    """Sort fields for query results."""

    SCORE = "score"
    FRESHNESS = "freshness"
    RELEVANCE = "relevance"


class KnowledgeQuery(_FrozenModel):
    """A structured knowledge retrieval query.

    Carries source routing, entity/time constraints, exact identifiers,
    filters, top-k, and evidence requirements.
    """

    query_id: str = Field(min_length=1)
    organization_id: UUID
    workspace_id: UUID
    principal_id: UUID
    text: str = Field(default="", max_length=10000)
    sources: tuple[QuerySource, ...] = Field(default_factory=tuple)
    entity_filters: tuple[str, ...] = Field(default_factory=tuple)
    time_from: datetime | None = None
    time_to: datetime | None = None
    exact_identifiers: dict[str, str] = Field(default_factory=dict)
    source_version_ids: tuple[str, ...] = Field(default_factory=tuple)
    classification_ceiling: str = "PUBLIC"
    top_k: int = Field(default=10, ge=1, le=1000)
    evidence_requirement: EvidenceRequirement = EvidenceRequirement.ANY
    sort_by: SortField = SortField.SCORE
    connector_filter: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class ScoreBreakdown(_FrozenModel):
    """Per-candidate score breakdown for a KnowledgeQuery result.

    Tracks SourceVersion/Locator/ACL/freshness scoring dimensions.
    """

    source_version_id: str = Field(min_length=1)
    locator_connector: str = Field(min_length=1)
    locator_uri: str = Field(min_length=1)
    acl_score: float = Field(ge=0.0, le=1.0)
    freshness_score: float = Field(ge=0.0, le=1.0)
    relevance_score: float = Field(ge=0.0, le=1.0)
    classification_score: float = Field(ge=0.0, le=1.0)
    total_score: float = Field(ge=0.0, le=1.0)
    acl_passes_recheck: bool = True
    classification_passes: bool = True


class QueryCandidate(_FrozenModel):
    """A single candidate result from the Knowledge Planner.

    Includes source version, locator, score breakdown, and ACL/freshness metadata.
    """

    source_version_id: str = Field(min_length=1)
    source_object_id: str = Field(min_length=1)
    connector: str = Field(min_length=1)
    uri: str = Field(min_length=1)
    content_digest: str = Field(min_length=1)
    classification: str = Field(default="PUBLIC")
    observed_at: datetime
    score: ScoreBreakdown
    is_revoked: bool = False
    acl_access_revoked: bool = False


class QueryPlan(_FrozenModel):
    """Planned query execution strategy.

    Generated by the Knowledge Planner based on the query sources,
    entity filters, and evidence requirements.
    """

    query_id: str = Field(min_length=1)
    source_type: QuerySource
    search_strategy: str = Field(min_length=1)
    filters: dict[str, Any] = Field(default_factory=dict)
    top_k: int = Field(ge=1, le=1000)
    needs_acl_recheck: bool = True
    needs_freshness_check: bool = True
    estimated_candidates: int = Field(default=0, ge=0)
